repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
        exclude: ".*\\.json"
    -   id: trailing-whitespace
    -   id: mixed-line-ending
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
    -   id: remove-crlf
    -   id: forbid-tabs
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
    - id: shellcheck
      # disable 'Can't follow non-constant source'
      args: ["--exclude=SC1090"]
      exclude: ".*zsh.*"
    - id: shfmt
      args: ["--indent", "4"]
      exclude: ".*zsh.*"
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    - id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
