repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: end-of-file-fixer
        exclude: ".*\\.json"
    -   id: trailing-whitespace
    -   id: mixed-line-ending
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
    -   id: remove-crlf
    -   id: forbid-tabs
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0  # or specific git tag
  hooks:
    - id: shellcheck
      args: ["--exclude=SC1090"]
      exclude: ".*zsh.*"
    - id: shfmt
      args: ["--indent", "4"]
      exclude: ".*zsh.*"
