#!/usr/bin/env python3
"""
Script used as a command line calculator.

Really, this can be used to execute arbitrary Python code, but the
intention is that it's aliased as 'noglob calc' and used as a CLI for
quick calculations.
"""

import argparse
import sys
from math import *  # noqa F401, F403


def parse_args(sys_args: list) -> str:
    parser = argparse.ArgumentParser(
        prog="calc", description="Command line calculator made with Python"
    )
    parser.add_argument("expression", nargs="*")
    return parser.parse_args(sys_args)


if __name__ == "__main__":
    args = parse_args(sys.argv[1:])
    print(eval(" ".join(args.expression)))
