#!/usr/bin/env bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ -n "$(command -v python3)" ]; then
    _py=python3
else
    _py=python
fi

ITEMS="$("${_py}" "${SCRIPT_DIR}/git_branch_list" -n "$@")"
PREVIEW_HEIGHT="$("${SCRIPT_DIR}/fzf_vertical_preview_height" "${ITEMS}")"
echo "${ITEMS}" | \
    fzf \
        --ansi \
        --preview-window="up,${PREVIEW_HEIGHT}" \
        --preview='git log --color --graph --oneline --decorate --simplify-by-decoration $(git for-each-ref --format='\''%(refname)'\'' refs/heads) $(git rev-list --reverse $(git merge-base HEAD $(git for-each-ref --format='\''%(refname)'\'' refs/heads | grep -v $(git symbolic-ref --short HEAD)))..HEAD) | GREP_COLORS="mt=01;30;47" grep --color=always -E "$(echo "{}" | cut -d" " -f2)|$"' | \
    cut -d' ' -f3
