#!/usr/bin/env python3
"""
Take the given paths and append (or prepend) to the system path string,
and return the new string.
"""

import os
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument("new_paths", nargs="+", help="Paths to add to the system path")
parser.add_argument(
    "-p",
    "--prepend",
    action="store_true",
    help="Prepend to system path instead of appending",
)
args = parser.parse_args()

if os.name == "nt":
    PATH_SEP = ";"
else:
    PATH_SEP = ":"

sys_paths = os.environ["PATH"].strip(PATH_SEP).split(PATH_SEP)
new_paths = [os.path.realpath(path) for path in args.new_paths]

for path in new_paths:
    if path not in sys_paths:
        if args.prepend:
            sys_paths = [path] + sys_paths
        else:
            sys_paths.append(path)

print(PATH_SEP.join(sys_paths) + PATH_SEP)
